# ── UART / Modbus ──────────────────────────────────
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=n
CONFIG_UART_CONSOLE=n

# ── Logs ───────────────────────────────────────────
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BACKEND_RTT=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_THREAD_STACK_INFO=y

# ── BLE ────────────────────────────────────────────
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="HMRA_Monitor"
CONFIG_BT_DEVICE_NAME_DYNAMIC=n
CONFIG_BT_NUS=y
CONFIG_BT_MAX_CONN=1
CONFIG_BT_GATT_CLIENT=y

# ── MTU étendu ─────────────────────────────────────
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251

# ── Buffers réduits pour tenir dans 64 Ko RAM ──────
CONFIG_BT_L2CAP_TX_BUF_COUNT=4
CONFIG_BT_ATT_TX_COUNT=4
CONFIG_BT_BUF_ACL_TX_COUNT=4

# ── Multithreading ──────────────────────────────────
CONFIG_MULTITHREADING=y
CONFIG_INIT_STACKS=y
CONFIG_THREAD_STACK_INFO=y